const mexicoBanks = [
  "BBVA México",
  "Santander México",
  "Banorte",
  "Citibanamex",
  "HSBC México",
  "Scotiabank",
  "Inbursa",
  "Banco Azteca",
  "BanCoppel",
  "BanBajío",
  "Afirme",
  "Banregio",
  "Mifel",
  "Multiva",
  "Bancrea",
  "Banca Mifel",
  "Actinver",
  "Banco Invex",
  "Monex",
  "Banco Famsa",
  "Banco del Bienestar",
  "Consubanco",
  "Compartamos Banco",
  "Banco Autofin",
  "Bansefi",
  "NU México",
  "Hey Banco",
  "Klar",
  "Albo",
  "Stori",
];

export default mexicoBanks;
